"""empty message

Revision ID: 5faa30860d8e
Revises: e9ba8c4b343c
Create Date: 2025-12-14 22:04:16.952401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5faa30860d8e'
down_revision = 'e9ba8c4b343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_key', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('s3_key')

    # ### end Alembic commands ###
