"""add email_confirmed in Users model

Revision ID: 8435d82d4699
Revises: bf3799bcf1b7
Create Date: 2026-01-10 18:27:31.787423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8435d82d4699'
down_revision = 'bf3799bcf1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
