"""initial

Revision ID: 9472cc1fb279
Revises: 
Create Date: 2025-08-03 21:41:30.721939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9472cc1fb279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=254), nullable=True),
    sa.Column('file_name', sa.String(length=254), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=254), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_of_accepting', sa.DateTime(), nullable=True),
    sa.Column('end_of_accepting', sa.DateTime(), nullable=True),
    sa.Column('summing_up', sa.DateTime(), nullable=True),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=254), nullable=True),
    sa.Column('winner_work_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['winner_work_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=20), nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('about_user', sa.String(length=900), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('juri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['juri_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('users')
    op.drop_table('nominations')
    op.drop_table('competitions')
    op.drop_table('artworks')
    # ### end Alembic commands ###
