"""add nominations status

Revision ID: db12118f9dad
Revises: 6747b8f9f2b7
Create Date: 2025-08-28 20:50:46.487601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db12118f9dad'
down_revision = '6747b8f9f2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nominations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nominations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
