"""empty message

Revision ID: e9ba8c4b343c
Revises: e34dddbf2f8d
Create Date: 2025-12-14 21:54:01.755582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ba8c4b343c'
down_revision = 'e34dddbf2f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.alter_column('file',
               existing_type=sa.VARCHAR(length=254),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.alter_column('file',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=254),
               existing_nullable=True)

    # ### end Alembic commands ###
